import type { Metadata } from 'next';
import BlogsLeave from './BlogsLeave';

export const metadata: Metadata = {
  title: 'Blogs',
  description: 'Generated by create next app 2',
};



export default function Blogs() {
  return(
    <BlogsLeave />
  )
}