import type { Metadata } from 'next';
import AboutLeave from './AboutLeave';

export const metadata: Metadata = {
  title: 'About Us',
  description: 'Generated by create next app 2',

};



export default function About() {
  return(
    <AboutLeave />
  )
}

