import type { Metadata } from 'next';
import LoginLeave from './LoginLeave';

export const metadata: Metadata = {
  title: 'Login',
  description: 'Generated by create next app 2',
};



export default function OurTeam() {
  return(
    <LoginLeave />
  )
}