import type { Metadata } from 'next';
import OurTeamLeave from './OurTeamLeave';

export const metadata: Metadata = {
  title: 'Our Team',
  description: 'Generated by create next app 2',
};



export default function OurTeam() {
  return(
    <OurTeamLeave />
  )
}