import type { Metadata } from 'next';
import ContactLeave from './ContactLeave';

export const metadata: Metadata = {
  title: 'Contact Us',
  description: 'Generated by create next app 2',
};



export default function Contact() {
  return(
    <ContactLeave />
  )
}