import type { Metadata } from 'next';
import { Roboto, Yellowtail } from 'next/font/google';
import '../../scss/global.scss';
import Footer from '@/components/Footer/Footer';
import Navbar from '@/components/Navbar/Navbar';
import { ReduxProvider } from '@/redux/provider';

const roboto = Roboto({ subsets: ['latin'], weight: ['400', '500', '700', '900'], display: 'swap', });
const yellowTail = Yellowtail({ subsets: ['latin'], weight: ['400'], display: 'swap', });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <ReduxProvider>
          <Navbar />
          {children}
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
