import type { Metadata } from 'next';
import ServicesLeave from './ServicesLeave';

export const metadata: Metadata = {
  title: 'Services',
  description: 'Generated by create next app 2',
};



export default function Contact() {
  return(
    <ServicesLeave />
  )
}