import type { Metadata } from 'next';
import ShopLeave from './ShopLeave';

export const metadata: Metadata = {
  title: 'Shop',
  description: 'Generated by create next app 2',
};



export default function Shop() {
  return(
    <ShopLeave />
  )
}