import type { Metadata } from 'next';
import RegisterLeave from './RegisterLeave';

export const metadata: Metadata = {
  title: 'Sign Up',
  description: 'Generated by create next app 2',
};



export default function Register() {
  return(
    <RegisterLeave />
  )
}